# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb68c5d98796acc4d1aa1a8967e8d3144059f364058fd070c4ef1144c47437b0a54a1be604c0b748e2c964f719b989380338b1471d93fd12fd66abcae50a311

test:
  secret_key_base: d2cec75d0a30c4e6e96e185e3ecbe57a04e79e7ea1efc6cfb358a4aafbe3529401878be1ac1ce978322c8d2502deb0d7b1272a725c916d6152abc3bd4e869f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
